Add a missing <iostream> include file
This fixes the following errors:

/home/certik/.hashdist/tmp/jali-4utau4njulvv/src/mesh/MeshDefs.hh: In function 'std::ostream& Jali::operator<<(std::ostream&, const Jali::Entity_kind&)':
/home/certik/.hashdist/tmp/jali-4utau4njulvv/src/mesh/MeshDefs.hh:99:6: error: no match for 'operator<<' (operand types are 'std::ostream {aka std::basic_ostream<char>}' and 'const char [2]')
   os << " " << Entity_kind_string(kind) << " ";
      ^