Use double braces to fix Intel compiler error
This fixes the following error, which is caused by the Intel compiler using
older header files for `std::vector`, that do not support the single brace
syntax:

.../jali/src/mesh/Mesh.cc(1719): error: no instance of overloaded function "std::vector<_Tp, _Alloc>::push_back [with _Tp=std::array<Jali::Entity_ID={int}, 2UL>, _Alloc=std::allocator<std::array<Jali::Entity_ID={int}, 2UL>>]" matches the argument list
            argument types are: ({...})
            object type is: std::vector<std::array<Jali::Entity_ID, 2UL>, std::allocator<std::array<Jali::Entity_ID, 2UL>>>
    facetpoints->push_back({0,1});
                 ^